const DEFAULT_ROLES = [
  {
    id: "role_owner",
    slug: "owner",
    name: "Owner",
    description: "Emergency control, system bootstrap, and protected recovery.",
    staff_level: 10,
    is_system: true,
    is_assignable: false,
    is_protected: true,
    deleted_at: null,
    deleted_by_user_id: null,
    delete_reason: null,
  },
  {
    id: "role_super_admin",
    slug: "super_admin",
    name: "Super Admin",
    description: "Full site administration and governance control.",
    staff_level: 9,
    is_system: true,
    is_assignable: true,
    is_protected: true,
    deleted_at: null,
    deleted_by_user_id: null,
    delete_reason: null,
  },
  {
    id: "role_admin",
    slug: "admin",
    name: "Admin",
    description: "User, role, settings, and content administration.",
    staff_level: 8,
    is_system: true,
    is_assignable: true,
    is_protected: false,
    deleted_at: null,
    deleted_by_user_id: null,
    delete_reason: null,
  },
  {
    id: "role_security_admin",
    slug: "security_admin",
    name: "Security Admin",
    description: "Two-factor auth, sessions, lockouts, audit, and security operations.",
    staff_level: 8,
    is_system: true,
    is_assignable: true,
    is_protected: false,
    deleted_at: null,
    deleted_by_user_id: null,
    delete_reason: null,
  },
  {
    id: "role_region_manager",
    slug: "region_manager",
    name: "Region Manager",
    description: "Region-scoped administrative control.",
    staff_level: 7,
    is_system: true,
    is_assignable: true,
    is_protected: false,
    deleted_at: null,
    deleted_by_user_id: null,
    delete_reason: null,
  },
  {
    id: "role_editor",
    slug: "editor",
    name: "Editor",
    description: "Editorial management and publishing.",
    staff_level: 6,
    is_system: true,
    is_assignable: true,
    is_protected: false,
    deleted_at: null,
    deleted_by_user_id: null,
    delete_reason: null,
  },
  {
    id: "role_auditor",
    slug: "auditor",
    name: "Auditor",
    description: "Read-only governance, audit, and security review.",
    staff_level: 5,
    is_system: true,
    is_assignable: true,
    is_protected: false,
    deleted_at: null,
    deleted_by_user_id: null,
    delete_reason: null,
  },
  {
    id: "role_author",
    slug: "author",
    name: "Author",
    description: "Authoring and self or assigned content management.",
    staff_level: 4,
    is_system: true,
    is_assignable: true,
    is_protected: false,
    deleted_at: null,
    deleted_by_user_id: null,
    delete_reason: null,
  },
  {
    id: "role_contributor",
    slug: "contributor",
    name: "Contributor",
    description: "Draft contribution only.",
    staff_level: 3,
    is_system: true,
    is_assignable: true,
    is_protected: false,
    deleted_at: null,
    deleted_by_user_id: null,
    delete_reason: null,
  },
  {
    id: "role_member",
    slug: "member",
    name: "Member",
    description: "Authenticated limited backoffice access.",
    staff_level: 2,
    is_system: true,
    is_assignable: true,
    is_protected: false,
    deleted_at: null,
    deleted_by_user_id: null,
    delete_reason: null,
  },
  {
    id: "role_viewer",
    slug: "viewer",
    name: "Viewer",
    description: "Minimal internal read access.",
    staff_level: 1,
    is_system: true,
    is_assignable: true,
    is_protected: false,
    deleted_at: null,
    deleted_by_user_id: null,
    delete_reason: null,
  },
];

export async function up(db) {
  await db.insertInto("roles").values(DEFAULT_ROLES).execute();
}

export async function down(db) {
  await db.deleteFrom("roles").where("id", "in", DEFAULT_ROLES.map((role) => role.id)).execute();
}

export { DEFAULT_ROLES };
